php:
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./app:/var/www/html
  links:
   - db

db:
  image: mysql:8.0.27
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phprs
   - MYSQL_DATABASE=phprs

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8888:80
  environment:
    - PMA_ARBITRARY=1